language: go
sudo: false
go:
  - 1.4
  - tip

before_script:
  - wget https://github.com/antirez/disque/archive/master.zip -O /tmp/disque.zip
  - cd /tmp && unzip disque.zip
  - cd /tmp/disque-master && make -j2
  - /tmp/disque-master/src/disque-server &
  - cd ${TRAVIS_BUILD_DIR}
before_install:
  - go get github.com/mattn/goveralls
script:
#  - go test -v ./disque
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=*example.go
